# Generated by Django 2.2 on 2019-11-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerAdmin', '0005_service_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
